### ISSUE TITLE
Port to PHP7

### ISSUE THREAD

**Issue by ymmt2005** [cybozu/php-yrmcds#7]
Ref. https://github.com/beberlei/whitewashing.de/blob/master/drafts/porting_extension_to_php7.rst
https://wiki.php.net/phpng-upgrading
https://speakerdeck.com/yoya/php7-swfed
http://qiita.com/hnw/items/d615e0d4122f247d4c75
http://php.net/manual/en/migration70.php
https://wiki.php.net/internals/engine/objects
http://www.phpinternalsbook.com/classes_objects.html

**Comment by ymmt2005** [comment]
Fixes to Custom Session Handler Return Values

    Any predicate functions implemented by custom session handlers that return either FALSE or -1 will be fatal errors. If any value from these functions other than a boolean, -1, or 0 is returned, then it will fail and an E_WARNING will be emitted.

**Comment by ymmt2005** [comment]
What's this?
> SessionUpdateTimestampHandlerInterface

**Comment by ymmt2005** [comment]
@nojima 
In #6, you added reference counting for persistent connections
in case of multiple Client objects sharing the same persistent
connection in a request.

It works, but I thin sharing the same connection in two or more
Clients is quite buggy!  Instead of reference counting, should we
raise an error for such cases?

**Comment by ymmt2005** [comment]
memo:

* Learn how to create custom objects.  
    カスタムオブジェクトの属性はリソース扱いにはならない。
    そりゃそうか。。でも persistent resource は persistent_list
    に ptr 扱いで登録して取り扱う、と。
* Investigate how (not) to use zend_fetch_resource().  
    リソース扱いにならないんだから、zend_fetch_resource() の出番もない。
* Revisit the fix for double-free bug in php-yrmcds.  
    See above comment.

**Comment by nojima** [comment]
> It works, but I think sharing the same connection in two or more
Clients is quite buggy! Instead of reference counting, should we
raise an error for such cases?

I implemented the reference counting logic because of the backward compatibility.
If breaking interface does not matter, we can forbid the connection sharing.

**Comment by ymmt2005** [comment]
Thanks.  At least, we should emit a warning.

**Comment by ymmt2005** [comment]
Implemented in [php7](https://github.com/cybozu/php-yrmcds/tree/php7) tree.
